export const mainTypes = {
    ADD_CHARACTERS: 'ADD_CHARACTERS',
    ADD_RIGTH_ANSWER: 'ADD_RIGTH_ANSWER',
    ADD_WRONG_ANSWER: 'ADD_WRONG_ANSWER',
    DELETE_WRONG_ANSWER: 'DELETE_WRONG_ANSWER',
};
