export const mainTypes = {
    ADD_CHARACTERS: 'ADD_CHARACTERS',
    ADD_RIGTH_ANSWER: 'ADD_RIGTH_ANSWER',
    ADD_WRONG_ANSWER: 'ADD_WRONG_ANSWER',
    CHANGE_FLAG: 'CHANGE_FLAG',
    CLEAR_CHARACTERS_STORE: 'CLEAR_CHARACTERS_STORE',
    CLEAR_ANSWERS_STORES: 'CLEAR_ANSWERS_STORES'
};
